//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffn_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appartenir
    {
        public string statut { get; set; }
        public int id_Nageur { get; set; }
        public int id_Equipe { get; set; }
    
        public virtual Equipe Equipe { get; set; }
        public virtual Nageur Nageur { get; set; }
    }
}
