//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ffn_site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Juge()
        {
            this.Evaluation = new HashSet<Evaluation>();
            this.EvaluationCompilee = new HashSet<EvaluationCompilee>();
            this.Juger = new HashSet<Juger>();
        }
    
        public int id { get; set; }
        public Nullable<int> rang { get; set; }
        public Nullable<bool> estArbitre { get; set; }
        public Nullable<int> id_Profil { get; set; }
        public Nullable<int> id_Personne { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationCompilee> EvaluationCompilee { get; set; }
        public virtual Personne Personne { get; set; }
        public virtual Profil Profil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Juger> Juger { get; set; }
    }
}
